platform :ios, '9.0'
use_frameworks!
target 'RouterApp' do
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :tag => '3.5.0'
pod 'ObjectMapper', '1.3.0'
pod 'RealmSwift', '~> 1.0.1'
pod 'Reachability'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON', :branch => 'swift2'
pod 'IQKeyboardManagerSwift', '4.0.3'
pod 'ReachabilitySwift'
end
